// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5OfjnS7CYb32CVrU-gUq62-sW4BV7elI',
    appId: '1:889129636799:web:15538387dd71aa3f93870a',
    messagingSenderId: '889129636799',
    projectId: 'hop-on-jkt',
    authDomain: 'hop-on-jkt.firebaseapp.com',
    storageBucket: 'hop-on-jkt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSb8_lbLZ6Dl6Jzx-dKM4ty-rjTJtHKCI',
    appId: '1:889129636799:android:68326e205551c69493870a',
    messagingSenderId: '889129636799',
    projectId: 'hop-on-jkt',
    storageBucket: 'hop-on-jkt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwRiPiedV97-j6bCkOkmIIgPKk1oep3Is',
    appId: '1:889129636799:ios:9eff310e1fe3af7a93870a',
    messagingSenderId: '889129636799',
    projectId: 'hop-on-jkt',
    storageBucket: 'hop-on-jkt.firebasestorage.app',
    iosBundleId: 'com.example.hopOnJkt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwRiPiedV97-j6bCkOkmIIgPKk1oep3Is',
    appId: '1:889129636799:ios:9eff310e1fe3af7a93870a',
    messagingSenderId: '889129636799',
    projectId: 'hop-on-jkt',
    storageBucket: 'hop-on-jkt.firebasestorage.app',
    iosBundleId: 'com.example.hopOnJkt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5OfjnS7CYb32CVrU-gUq62-sW4BV7elI',
    appId: '1:889129636799:web:a26e36dd8f2731fb93870a',
    messagingSenderId: '889129636799',
    projectId: 'hop-on-jkt',
    authDomain: 'hop-on-jkt.firebaseapp.com',
    storageBucket: 'hop-on-jkt.firebasestorage.app',
  );
}
