// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNl9ExgW2Va4GmwMjRmrc9aBXy6r2Ipw4',
    appId: '1:489263431619:web:b442df2d80e1be08220776',
    messagingSenderId: '489263431619',
    projectId: 'hop-on-uk',
    authDomain: 'hop-on-uk.firebaseapp.com',
    storageBucket: 'hop-on-uk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWWKV64_rC-uvW8INHdyEAxs1ylGhg0dg',
    appId: '1:489263431619:android:a943ca0cd25338a8220776',
    messagingSenderId: '489263431619',
    projectId: 'hop-on-uk',
    storageBucket: 'hop-on-uk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW-TA76AbmWgip_Ck_caw0kKjmrVANk_M',
    appId: '1:489263431619:ios:0839250ff5bf3cb0220776',
    messagingSenderId: '489263431619',
    projectId: 'hop-on-uk',
    storageBucket: 'hop-on-uk.firebasestorage.app',
    iosBundleId: 'com.example.hopOnUk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW-TA76AbmWgip_Ck_caw0kKjmrVANk_M',
    appId: '1:489263431619:ios:0839250ff5bf3cb0220776',
    messagingSenderId: '489263431619',
    projectId: 'hop-on-uk',
    storageBucket: 'hop-on-uk.firebasestorage.app',
    iosBundleId: 'com.example.hopOnUk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNl9ExgW2Va4GmwMjRmrc9aBXy6r2Ipw4',
    appId: '1:489263431619:web:7915721bf23876d7220776',
    messagingSenderId: '489263431619',
    projectId: 'hop-on-uk',
    authDomain: 'hop-on-uk.firebaseapp.com',
    storageBucket: 'hop-on-uk.firebasestorage.app',
  );
}
